# Generated by Django 6.0.6 on 2026-06-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
        ('sources', '0002_country_alter_jobsite_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cv_profiles', to='sources.country'),
        ),
    ]
