# Generated by Django 6.0.6 on 2026-06-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('daily_plan', models.PositiveIntegerField(default=0)),
                ('processed_today', models.PositiveIntegerField(default=0)),
                ('color_status', models.CharField(default='gray', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=300)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('technology', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_signatures', to='sources.jobsite')),
            ],
            options={
                'ordering': ['job_site__name', 'search_text'],
            },
        ),
    ]
