# Generated by Django 6.0.6 on 2026-06-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_seed_initial_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='color_status',
            field=models.CharField(choices=[('problem', 'Problem'), ('attention', 'Attention'), ('ok', 'OK'), ('inactive', 'Inactive'), ('broken', 'Broken')], default='inactive', max_length=20),
        ),
    ]
