# Generated by Django 6.0.6 on 2026-06-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_recalculate_jobsite_color_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sort_order', models.PositiveSmallIntegerField(unique=True, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='jobsite',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Сайт вакансий', 'verbose_name_plural': 'Сайты вакансий'},
        ),
        migrations.AlterModelOptions(
            name='searchsignature',
            options={'ordering': ['job_site__name', 'search_text'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='color_status',
            field=models.CharField(choices=[('problem', 'Проблема'), ('attention', 'Внимание'), ('ok', 'OK'), ('inactive', 'Неактивен'), ('broken', 'Сломан')], default='inactive', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_sites', to='sources.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='daily_plan',
            field=models.PositiveIntegerField(default=0, verbose_name='План в день'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='processed_today',
            field=models.PositiveIntegerField(default=0, verbose_name='Обработано сегодня'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_signatures', to='sources.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='job_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_signatures', to='sources.jobsite', verbose_name='Сайт вакансий'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='search_text',
            field=models.CharField(max_length=300, verbose_name='Поисковый запрос'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='technology',
            field=models.CharField(blank=True, max_length=150, verbose_name='Технология'),
        ),
        migrations.AlterField(
            model_name='searchsignature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
    ]
