# Generated by Django 6.0.6 on 2026-06-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=150)),
                ('provider_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='new', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='cvs.cvprofile')),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posts', to='sources.jobsite')),
            ],
            options={
                'ordering': ['-added_at', 'title'],
            },
        ),
    ]
