# Generated by Django 6.0.6 on 2026-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_jobpost_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Статус вакансии',
                'verbose_name_plural': 'Статусы вакансий',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-added_at', 'title'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
